id:
  type: number
  restriction_mode: A
  constant: true
  required: true
poll_id:
  type: relation
  to: poll/config_id
  reference: poll
  required: true
  restriction_mode: A
option_ids:
  type: relation-list
  to: poll_config_option/poll_config_id
  on_delete: CASCADE
  restriction_mode: A
max_options_amount:
  type: number
  default: 0
  restriction_mode: A
min_options_amount:
  type: number
  default: 0
  restriction_mode: A
allow_abstain:
  type: boolean
  default: true
  restriction_mode: A
